### ISSUE TITLE
Pantalaimon doesn't handle missing optional 'rooms' key in sync

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/pantalaimon#109]
Since https://github.com/matrix-org/synapse/issues/10479 was closed, Synapse may not send all keys down sync. However, this seems to upset pan.

```
[2021-10-12 17:00:34.104827] INFO: pantalaimon: Trying to decrypt sync
[2021-10-12 17:00:34.105011] INFO: pantalaimon: Decrypting sync
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py", line 777, in sync
    json_response = await self.decrypt_body(client, json_response)
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py", line 734, in decrypt_body
    return await asyncio.wait_for(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py", line 727, in decrypt_loop
    return decryption_method(body, ignore_failures=False)
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/client.py", line 940, in decrypt_sync_body
    for room_id, room_dict in body["rooms"]["join"].items():
KeyError: 'rooms'
```

**Comment by Half-Shot** [comment]
This seems to have been fixed in a recent version of pan
