### ISSUE TITLE
panctl error: `gi` seems to have renamed to `pgi`

### ISSUE THREAD

**Issue by ltlnx** [matrix-org/pantalaimon#112]
**Describe the bug**
The module `gi` seems to have renamed to `pgi`.
Not sure if it's specific for my build or a global rename.

**To Reproduce**
```
$ panctl
Traceback (most recent call last):
  File "/home/ltlnx/anaconda3/bin/panctl", line 5, in <module>
    from pantalaimon.panctl import main
  File "/home/ltlnx/anaconda3/lib/python3.8/site-packages/pantalaimon/panctl.py", line 26, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'

$ python
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import GLib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
>>> from pgi.repository import GLib
>>> 

```

**Comment by Mexxerio** [comment]
Having the same issue

**Comment by disconn3ct** [comment]
Docker container is also affected
