### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by tfreedman** [matrix-org/pantalaimon#124]
I just tried setting up pantalaimon in docker, and can't get panctl to run from within the container.

Docker commands: 
`docker run -d --restart=unless-stopped -v /home/core/data:/data -p 8008:8008 matrixdotorg/pantalaimon`
`docker exec -it <instanceID> /bin/bash`

```
# panctl
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/panctl.py", line 28, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/panctl", line 5, in <module>
    from pantalaimon.panctl import main
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/panctl.py", line 30, in <module>
    from pgi.repository import GLib
ModuleNotFoundError: No module named 'pgi'
```

I'm assuming https://github.com/matrix-org/pantalaimon/pull/122/commits/86060a2f7561d40bd142c8bc1847e151c3d40dff didn't totally fix things.

**Comment by aspacca** [comment]
https://gist.github.com/aspacca/6320d86692353001f7a0be1ae4471113

**Comment by JeremyMahieu** [comment]
> https://gist.github.com/aspacca/6320d86692353001f7a0be1ae4471113

This gives me
```
Step 8/22 : RUN pip wheel .[ui] --wheel-dir /wheels --find-links /wheels
 ---> Running in xxxxxxxxxx
ERROR: Directory '.[ui]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
ERROR: Service 'pantaleimon' failed to build: The command '/bin/sh -c pip wheel .[ui] --wheel-dir /wheels --find-link
```

**Comment by JeremyMahieu** [comment]
> do you run from the build from the root of the git repo?
What does it matter, you're pulling all the code from pip 
```
RUN pip --no-cache-dir install --find-links /wheels --no-index pantalaimon
RUN pip --no-cache-dir install --find-links /wheels --no-index pantalaimon[ui]
```

**Comment by aspacca** [comment]
> What does it matter, you're pulling all the code from pip

not in the builder: https://gist.github.com/aspacca/6320d86692353001f7a0be1ae4471113#file-dockerfile-L13-L15
```
COPY . /app

RUN pip wheel .[ui] --wheel-dir /wheels --find-links /wheels
```

that's exactly where you have the error

**Comment by JeremyMahieu** [comment]
Don't get me wrong, I didn't modify your gist. Here is the complete result:

1. Used your gist as `Dockerfile`
2. Made a `docker-compose.yml`
3. Started it with command `docker-compose up --build`


```
version: '3.3'

services:
  pantalaimon:
    build: .
    container_name: pantalaimon
    restart: unless-stopped
    volumes:
     - ./data:/data
    ports:
     - 8124:8124
```

```
$ docker-compose up --build
Building pantalaimon
Step 1/22 : FROM python:3.8-slim-bullseye AS builder
 ---> 61c56c60bb49
Step 2/22 : RUN mkdir -p /app
 ---> Using cache
 ---> a92d1585ff31
Step 3/22 : RUN apt-get update && apt-get install -y git gcc clang cmake g++ pkg-config python3-dev wget libcairo2-dev libgirepository1.0-dev libdbus-1-3 libdbus-1-dev
 ---> Using cache
 ---> 7c90eaf6b3fc
Step 4/22 : WORKDIR /app
 ---> Using cache
 ---> 6b50fa3344b1
Step 5/22 : RUN wget https://gitlab.matrix.org/matrix-org/olm/-/archive/master/olm-master.tar.bz2     && tar -xvf olm-master.tar.bz2     && cd olm-master && make && make PREFIX="/usr" install
 ---> Using cache
 ---> 697925527e27
Step 6/22 : RUN pip --no-cache-dir install --upgrade pip setuptools wheel
 ---> Using cache
 ---> 3c19921e5934
Step 7/22 : COPY . /app
 ---> a16c24218f89
Step 8/22 : RUN pip wheel .[ui] --wheel-dir /wheels --find-links /wheels
 ---> Running in 730471605f13
ERROR: Directory '.[ui]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
ERROR: Service 'pantalaimon' failed to build: The command '/bin/sh -c pip wheel .[ui] --wheel-dir /wheels --find-links /wheels' returned a non-zero code: 1
```

**Comment by JeremyMahieu** [comment]
@aspacca You're absolutely correct, I didn't spot that and I didn't copy the git repsitory to my folder. I feel like this is all a bit off topic. Though. Perhaps your gist should become the actual dockerfile, see #131

**Comment by jph** [comment]
I'm not sure I'm following the above replies. Was there a tried and true solution for this? As it stands, Pantalaimon is unusable for me, as I cannot operate `panctl` at all.

**Comment by aspacca** [comment]
@jph
starting the container building from the dockefile at https://gist.github.com/aspacca/6320d86692353001f7a0be1ae4471113 solves the issue

it starts a tmux session that you can attach and from there start a new one running `panctl`

**Comment by jph** [comment]
Thanks @aspacca, good workaround.
