### ISSUE TITLE
UnboundLocalError: local variable 'token' referenced before assignment

### ISSUE THREAD

**Issue by jaller94** [matrix-org/pantalaimon#129]
pantalaimon: version 0.10.4
Installation method: pip
OS: Rasbian

## Config
```
[local-matrix]
Homeserver = https://iot-staging.ems.host
ListenAddress = localhost
ListenPort = 8009
```

## Error

```
Mai 24 11:28:25 raspberrypi pantalaimon[363]: [2022-05-24 09:28:25.897364] ERROR: pantalaimon: No recommended backend was available. Install a recommended 3rd party backend package; or, ins>
Mai 24 11:28:25 raspberrypi pantalaimon[363]: Traceback (most recent call last):
Mai 24 11:28:25 raspberrypi pantalaimon[363]:   File "/home/cih/.local/bin/pantalaimon", line 8, in <module>
Mai 24 11:28:25 raspberrypi pantalaimon[363]:     sys.exit(main())
Mai 24 11:28:25 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return self.main(*args, **kwargs)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     rv = self.invoke(ctx)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return ctx.invoke(self.callback, **ctx.params)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return __callback(*args, **kwargs)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return f(get_current_context(), *args, **kwargs)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/pantalaimon/main.py", line 277, in main
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     asyncio.run(daemon(context, log_level, debug_encryption, config, data_path))
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return loop.run_until_complete(main)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     return future.result()
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/pantalaimon/main.py", line 213, in daemon
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     proxy, runner, site = await init(data_dir, server_conf, pan_queue, ui_queue)
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/pantalaimon/main.py", line 53, in init
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     proxy = ProxyDaemon(
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "<attrs generated init pantalaimon.daemon.ProxyDaemon>", line 18, in __init__
Mai 24 11:28:26 raspberrypi pantalaimon[363]:   File "/home/cih/.local/lib/python3.9/site-packages/pantalaimon/daemon.py", line 138, in __attrs_post_init__
Mai 24 11:28:26 raspberrypi pantalaimon[363]:     if not token:
Mai 24 11:28:26 raspberrypi pantalaimon[363]: UnboundLocalError: local variable 'token' referenced before assignment
```

**Comment by jaller94** [comment]
Workaround:
* Add `UseKeyring=False` to the config.
