### ISSUE TITLE
No such table: storeversion exception on fresh configuration

### ISSUE THREAD

**Issue by lbeltrame** [matrix-org/pantalaimon#17]
Trying to log in with Quaternion, fresh configuration:

```python
[2019-07-27 07:21:05.320614] INFO: pantalaimon: New user logging in: XXX
[2019-07-27 07:21:05.787312] INFO: pantalaimon: User: XXX succesfully logged in, starting a background sync client.
[2019-07-27 07:21:05.805770] INFO: pantalaimon: Indexing disabled.
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: storeversion
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib64/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 628, in login
    await self.start_pan_client(access_token, user, user_id, password)
  File "/usr/local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 554, in start_pan_client
    response = await pan_client.login(password, "pantalaimon")
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 408, in login
    return await self._send(LoginResponse, method, path, data)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 354, in _send
    await self.receive_response(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 329, in receive_response
    super().receive_response(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 848, in receive_response
    self._handle_login(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 506, in _handle_login
    self.load_store()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 307, in load_store
    self.config.store_name
  File "<attrs generated init 589b43e613ff858f2bf79dfa91f9c2f209198d72>", line 7, in __init__
    self.__attrs_post_init__()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/store/database.py", line 570, in __attrs_post_init__
    store_version = self._get_store_version()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/store/database.py", line 583, in _get_store_version
    defaults={"version": self.store_version}
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6124, in get_or_create
    return query.get(), False
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6496, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 1856, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2027, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2962, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/playhouse/sqliteq.py", line 248, in execute_sql
    return self._execute(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2956, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: storeversion
```

And everything breaks after that. This is pantalaimon built off git from a few minutes ago.

**Comment by lbeltrame** [comment]
Subsequent attempt at logins give these exceptions:

```
[2019-07-27 07:29:22.755498] INFO: pantalaimon: Indexing disabled.
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6496, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 4024, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6124, in get_or_create
    return query.get(), False
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6501, in get
    (clone.model, sql, params))
nio.store.models.StoreVersionDoesNotExist: <Model: StoreVersion> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."version" FROM "storeversion" AS "t1" LIMIT ? OFFSET ?
Params: [1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib64/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 628, in login
    await self.start_pan_client(access_token, user, user_id, password)
  File "/usr/local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 554, in start_pan_client
    response = await pan_client.login(password, "pantalaimon")
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 408, in login
    return await self._send(LoginResponse, method, path, data)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 354, in _send
    await self.receive_response(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/async_client.py", line 329, in receive_response
    super().receive_response(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 848, in receive_response
    self._handle_login(response)
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 506, in _handle_login
    self.load_store()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/client/base_client.py", line 307, in load_store
    self.config.store_name
  File "<attrs generated init 589b43e613ff858f2bf79dfa91f9c2f209198d72>", line 7, in __init__
    self.__attrs_post_init__()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/store/database.py", line 570, in __attrs_post_init__
    store_version = self._get_store_version()
  File "/usr/local/lib/python3.7/site-packages/matrix_nio-0.4.1-py3.7.egg/nio/store/database.py", line 583, in _get_store_version
    defaults={"version": self.store_version}
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/peewee.py", line 6129, in get_or_create
    with cls._meta.database.atomic():
  File "/usr/local/lib/python3.7/site-packages/peewee-3.9.6-py3.7-linux-x86_64.egg/playhouse/sqliteq.py", line 295, in __unsupported__
    raise ValueError('This method is not supported by %r.' % type(self))
ValueError: This method is not supported by <class 'playhouse.sqliteq.SqliteQueueDatabase'>.
```

**Comment by poljar** [comment]
That's certainly weird, I just tested with a completely new setup and it created the store version table successfully.

Even weirder is that the function that tries to get the store version and is failing because the table doesn't exist creates the table before it tries to fetch the version from it: https://github.com/poljar/matrix-nio/blob/master/nio/store/database.py#L586

Oh wait a minute, latest git had some commits missing. I pushed the tag but didn't push the commits. Please try again now or the version on pypi.

**Comment by lbeltrame** [comment]
Indeed it works now.
