### ISSUE TITLE
pantalaimon wont start

### ISSUE THREAD

**Issue by ReK2Fernandez** [matrix-org/pantalaimon#18]
pantalaimon --log-level debug
Traceback (most recent call last):
  File "/usr/bin/pantalaimon", line 11, in <module>
    load_entry_point('pantalaimon==0.2', 'console_scripts', 'pantalaimon')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/pantalaimon-0.2-py3.7.egg/pantalaimon/main.py", line 28, in <module>
    from pantalaimon.daemon import ProxyDaemon
  File "/usr/lib/python3.7/site-packages/pantalaimon-0.2-py3.7.egg/pantalaimon/daemon.py", line 30, in <module>
    from pantalaimon.client import (
  File "/usr/lib/python3.7/site-packages/pantalaimon-0.2-py3.7.egg/pantalaimon/client.py", line 24, in <module>
    from nio import (
ImportError: cannot import name 'RoomKeyRequest' from 'nio' (/usr/lib/python3.7/site-packages/nio/__init__.py)

**Comment by poljar** [comment]
It seems that you are using the latest master of pantalaimon. Latest master requires the latest nio version. Could you try updating nio?

**Comment by poljar** [comment]
Closing due to inactivity.
