### ISSUE TITLE
Crash on handling /sync

### ISSUE THREAD

**Issue by ara4n** [matrix-org/pantalaimon#3]
Tried to sync `@matthew2:matrix.org` with a naive GET /sync:

```
Error handling request
Traceback (most recent call last):
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "pantalaimon/daemon.py", line 211, in sync
    response = await client.sync(timeout, sync_filter)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/client/async_client.py", line 252, in sync
    return await self._send(SyncResponse, method, path)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/client/async_client.py", line 168, in _send
    response_data
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/client/async_client.py", line 150, in create_matrix_response
    response = response_class.from_dict(parsed_dict)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/responses.py", line 131, in wrapper
    return f(cls, parsed_dict, *args, **kwargs)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/responses.py", line 1055, in from_dict
    parsed_dict["rooms"], max_events)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/responses.py", line 1023, in _get_room_info
    max_events
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/responses.py", line 951, in _get_join_info
    timeline_events, timeline_max
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/responses.py", line 841, in _get_room_events
    event = Event.parse_event(event_dict)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/events.py", line 106, in parse_event
    return RoomMessage.parse_event(event_dict)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/events.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/events.py", line 690, in parse_event
    event = RoomMessageUnknown.from_dict(parsed_dict)
  File "/Users/matthew/workspace/pantalaimon/env/lib/python3.7/site-packages/nio/events.py", line 817, in from_dict
    parsed_dict["content"]["type"],
KeyError: 'type'
```

**Comment by poljar** [comment]
This should be fixed in nio by https://github.com/poljar/matrix-nio/commit/092792e37763210e68568ebbed967c89e313b9f9.
