### ISSUE TITLE
Can't build pantalaimon

### ISSUE THREAD

**Issue by jonnius** [matrix-org/pantalaimon#47]
Is Pantalaimon meant to be built with Python 2 or 3? The build fails for me with both on Ubuntu 16.04:

# Python 2.7 (setup.py or pip)
```
$ python2 setup.py install --prefix $INSTALL_DIR
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    with open("README.md", encoding="utf-8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

# Python 3.5
## setup.py
```
$ python3 setup.py install --prefix $INSTALL_DIR
running install
running bdist_egg
running egg_info
writing requirements to pantalaimon.egg-info/requires.txt
writing top-level names to pantalaimon.egg-info/top_level.txt
writing entry points to pantalaimon.egg-info/entry_points.txt
writing pantalaimon.egg-info/PKG-INFO
writing dependency_links to pantalaimon.egg-info/dependency_links.txt
reading manifest file 'pantalaimon.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
warning: no files found matching 'doc/man/pantalaimon.8'
warning: no files found matching 'doc/man/pantalaimon.5'
warning: no files found matching 'doc/man/panctl.1'
writing manifest file 'pantalaimon.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying pantalaimon/thread_messages.py -> build/lib/pantalaimon
copying pantalaimon/main.py -> build/lib/pantalaimon
copying pantalaimon/client.py -> build/lib/pantalaimon
copying pantalaimon/store.py -> build/lib/pantalaimon
copying pantalaimon/config.py -> build/lib/pantalaimon
copying pantalaimon/__init__.py -> build/lib/pantalaimon
copying pantalaimon/log.py -> build/lib/pantalaimon
copying pantalaimon/daemon.py -> build/lib/pantalaimon
copying pantalaimon/ui.py -> build/lib/pantalaimon
copying pantalaimon/index.py -> build/lib/pantalaimon
copying pantalaimon/panctl.py -> build/lib/pantalaimon
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/thread_messages.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/main.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/client.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/store.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/config.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/__init__.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/log.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/daemon.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/ui.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/index.py -> build/bdist.linux-x86_64/egg/pantalaimon
copying build/lib/pantalaimon/panctl.py -> build/bdist.linux-x86_64/egg/pantalaimon
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/thread_messages.py to thread_messages.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/main.py to main.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/client.py to client.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/store.py to store.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/config.py to config.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/log.py to log.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/daemon.py to daemon.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/ui.py to ui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/index.py to index.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pantalaimon/panctl.py to panctl.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pantalaimon.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/pantalaimon-0.5.1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pantalaimon-0.5.1-py3.5.egg
removing '/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg' (and everything under it)
creating /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg
Extracting pantalaimon-0.5.1-py3.5.egg to /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages
pantalaimon 0.5.1 is already the active version in easy-install.pth
Installing panctl script to /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/bin
Installing pantalaimon script to /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/bin

Installed /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg
Processing dependencies for pantalaimon==0.5.1
Searching for cachetools>=3.0.0prompt_toolkit>2<4
Reading https://pypi.python.org/simple/cachetools/
Best match: cachetools 4.1.0
Downloading https://files.pythonhosted.org/packages/30/62/88fda08df9053141647b6941141b71b4c2a23d0fabab485feb917428ab46/cachetools-4.1.0.tar.gz#sha256=1d057645db16ca7fe1f3bd953558897603d6f0b9c51ed9d11eb4d071ec4e2aab
Processing cachetools-4.1.0.tar.gz
Writing /tmp/easy_install-y84ry1st/cachetools-4.1.0/setup.cfg
Running cachetools-4.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y84ry1st/cachetools-4.1.0/egg-dist-tmp-2p1pz047
  File "build/bdist.linux-x86_64/egg/pantalaimon/main.py", line 114
    logger.debug(f"Router got message {message}")
                                               ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/client.py", line 285
    logger.info(f"Adding media info for {mxc_server}/{mxc_path} to the store")
                                                                            ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/config.py", line 65
    f"Invalid URL scheme {value.scheme}. " f"Only HTTP(s) URLs are allowed"
                                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/daemon.py", line 119
    "pantalaimon", f"{user_id}-{device_id}-token"
                                                ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/ui.py", line 473
    f"There are unverified devices in the room "
                                               ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/index.py", line 311
    raise InvalidQueryError(f"Invalid search term: {search_term}")
                                                                ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pantalaimon/panctl.py", line 51
    message = f"Error: {message} " f"(see help)"
                                 ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/main.py", line 114
    logger.debug(f"Router got message {message}")
                                               ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/client.py", line 285
    logger.info(f"Adding media info for {mxc_server}/{mxc_path} to the store")
                                                                            ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/config.py", line 65
    f"Invalid URL scheme {value.scheme}. " f"Only HTTP(s) URLs are allowed"
                                         ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/daemon.py", line 119
    "pantalaimon", f"{user_id}-{device_id}-token"
                                                ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/ui.py", line 473
    f"There are unverified devices in the room "
                                               ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/index.py", line 311
    raise InvalidQueryError(f"Invalid search term: {search_term}")
                                                                ^
SyntaxError: invalid syntax

  File "/home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/pantalaimon-0.5.1-py3.5.egg/pantalaimon/panctl.py", line 51
    message = f"Error: {message} " f"(see help)"
                                 ^
SyntaxError: invalid syntax

no previously-included directories found matching 'docs/_build'
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Removing /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/UNKNOWN-0.0.0-py3.5.egg
Moving UNKNOWN-0.0.0-py3.5.egg to /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /home/jonatan/Entwicklung/fluffychat/build/arm-linux-gnueabihf/pantalaimon/install/lib/python3.5/site-packages/UNKNOWN-0.0.0-py3.5.egg
error: The 'cachetools>=3.0.0prompt_toolkit>2<4' distribution was not found and is required by pantalaimon
```

## pip
```
$ python3 -m pip install pantalaimon -t $INSTALL_DIR
Collecting pantalaimon
  Using cached pantalaimon-0.5.1-py3-none-any.whl (45 kB)
Collecting attrs
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting matrix-nio[e2e]>=0.8.0
  Using cached matrix_nio-0.10.0-py3-none-any.whl (149 kB)
Collecting logbook
  Using cached Logbook-1.5.3.tar.gz (85 kB)
Collecting appdirs
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting keyring
  Using cached keyring-20.0.1-py2.py3-none-any.whl (31 kB)
Collecting aiohttp
  Using cached aiohttp-2.3.10-cp35-cp35m-manylinux1_x86_64.whl (649 kB)
Collecting janus
  Using cached janus-0.3.2-py3-none-any.whl (6.7 kB)
Collecting cachetools>=3.0.0prompt_toolkit>2<4
  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting peewee
  Using cached peewee-3.13.2.tar.gz (870 kB)
Collecting click
  Using cached click-7.1.1-py2.py3-none-any.whl (82 kB)
Collecting h2
  Using cached h2-3.2.0-py2.py3-none-any.whl (65 kB)
Collecting unpaddedbase64
  Using cached unpaddedbase64-1.1.0-py2.py3-none-any.whl (3.3 kB)
Collecting pycryptodome
  Using cached pycryptodome-3.9.7-cp35-cp35m-manylinux1_x86_64.whl (13.7 MB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting jsonschema
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting dataclasses; python_version < "3.7"
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting h11
  Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
Collecting python-olm>=3.1.0; extra == "e2e"
  Using cached python-olm-3.1.3.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2sp6mu5w/python-olm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2sp6mu5w/python-olm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2sp6mu5w/python-olm/pip-egg-info
         cwd: /tmp/pip-install-2sp6mu5w/python-olm/
    Complete output (48 lines):
    
    Installed /tmp/pip-install-2sp6mu5w/python-olm/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.20
    Downloading https://files.pythonhosted.org/packages/0f/86/e19659527668d70be91d0369aeaa055b4eb396b0f387a4f92293a20035bd/pycparser-2.20.tar.gz#sha256=2d475327684562c3a96cc71adf7dc8c4f0565175cf86b6d7a404ff4c771f15f0
    Processing pycparser-2.20.tar.gz
    Writing /tmp/easy_install-ssy1_q69/pycparser-2.20/setup.cfg
    Running pycparser-2.20/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ssy1_q69/pycparser-2.20/egg-dist-tmp-or2lmh96
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-35: module references __file__
    pycparser.ply.__pycache__.lex.cpython-35: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-35: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-35: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-35: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-35: module references __file__
    creating /tmp/pip-install-2sp6mu5w/python-olm/.eggs/pycparser-2.20-py3.5.egg
    Extracting pycparser-2.20-py3.5.egg to /tmp/pip-install-2sp6mu5w/python-olm/.eggs
    
    Installed /tmp/pip-install-2sp6mu5w/python-olm/.eggs/pycparser-2.20-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2sp6mu5w/python-olm/setup.py", line 30, in <module>
        zip_safe=False
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-2sp6mu5w/python-olm/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-install-2sp6mu5w/python-olm/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-install-2sp6mu5w/python-olm/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 22, in execfile
        src = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 62: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by poljar** [comment]
I'm afraid that we require Python 3.6+.

**Comment by jonnius** [comment]
Thanks for the fast reply. Now I am using [ppa:deadsnakes/ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=xenial) to install a newer Python in Ubuntu 16.04 with the following result:
### Python 3.6
Same error as with Python 3.5:
```
[…]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 62: ordinal not in range(128)
```
### Python 3.7
```
Collecting pantalaimon
  Using cached pantalaimon-0.5.1-py3-none-any.whl (45 kB)
[…]
Collecting python-olm>=3.1.0; extra == "e2e"
  Using cached python-olm-3.1.3.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jiwxxkwv/python-olm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jiwxxkwv/python-olm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jiwxxkwv/python-olm/pip-egg-info
         cwd: /tmp/pip-install-jiwxxkwv/python-olm/
    Complete output (119 lines):
    
    Installed /tmp/pip-install-jiwxxkwv/python-olm/.eggs/cffi-1.14.0-py3.7-linux-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.20
    Downloading https://files.pythonhosted.org/packages/0f/86/e19659527668d70be91d0369aeaa055b4eb396b0f387a4f92293a20035bd/pycparser-2.20.tar.gz#sha256=2d475327684562c3a96cc71adf7dc8c4f0565175cf86b6d7a404ff4c771f15f0
    Processing pycparser-2.20.tar.gz
    Writing /tmp/easy_install-jqlfg9fc/pycparser-2.20/setup.cfg
    Running pycparser-2.20/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jqlfg9fc/pycparser-2.20/egg-dist-tmp-hdsgzvrz
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-jqlfg9fc/pycparser-2.20/setup.py", line 65, in <module>
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
        code = marshal.load(f)
    ValueError: bad marshal data (unknown type code)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jiwxxkwv/python-olm/setup.py", line 30, in <module>
        zip_safe=False
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-jqlfg9fc/pycparser-2.20/setup.py", line 65, in <module>
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
        code = marshal.load(f)
    ValueError: bad marshal data (unknown type code)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
### Python 3.8 & 3.9
```
[…]
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
```
Looks like the package `python3-distutils` is missing, which is neither installable from the PPA nor the Xenial repos.

**Comment by jonnius** [comment]
Ok, forget about it, I got around the issue in Python 3.7 by installing setuptools via pip instead of apt.
