### ISSUE TITLE
Error running panctl in docker

### ISSUE THREAD

**Issue by SeveHo** [matrix-org/pantalaimon#53]
Hi,

Thanks for providing a docker based setup!
Starting pantalaimon works so far and it is listening successfully on the specified ports.
 
But when I try using _**panctl**_ inside the docker machine I get the following error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/panctl", line 5, in <module>
    from pantalaimon.panctl import main
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/panctl.py", line 26, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

Any Ideas?
Trying suggestions from here didn't work for me: https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python

**Comment by poljar** [comment]
The docker image is optimized for bot deployments and doesn't install the UI dependencies of pantalaimon. The dependencies to make the UI and panctl work are listed [here](https://github.com/matrix-org/pantalaimon/blob/master/setup.py#L34).

**Comment by SeveHo** [comment]
I see. Thank you!

**Comment by dmsimard** [comment]
Hi o/

Chiming in to say that I noticed this as well. The intent was to use panctl to verify sessions a bit like mentioned in [this blog post](https://www.cogitri.dev/posts/10-pantalaimon-setup/).

It would be convenient to have it inside the image for sure though it does seem like there are a lot of development libraries required to be able to run ``pip install pantalaimon[ui]`` successfully which might be why it's not included in the first place ?

@poljar Would you accept a pull request that provides a Dockerfile in which the UI dependencies are also installed ? I don't personally mind if it yields an image that is a bit heavier and I could see it being useful for other users.

**Comment by poljar** [comment]
I don't mind extra docker files, no.

**Comment by BBaoVanC** [comment]
Maybe it can just be a separate tag like "ui" or something (so like `latest-ui`, and `v0.10.3-ui`)
