### ISSUE TITLE
ImportError: libolm.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by almereyda** [matrix-org/pantalaimon#6]
Given `pantalaimon` is installed similarily to #4 and #5, `libolm.so.3` finds itself in `/usr/local/lib64/`.
Unfortunately `pantalaimon` does not pick it up initially, and running it states:

```
Traceback (most recent call last):
  File "/home/ya/.local/bin/pantalaimon", line 11, in <module>
    load_entry_point('pantalaimon==0.1', 'console_scripts', 'pantalaimon')()
  File "/home/ya/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ya/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ya/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ya/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ya/.local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 14, in <module>
    from nio import (
  File "/home/ya/.local/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/home/ya/.local/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig, logged_in, store_loaded
  File "/home/ya/.local/lib/python3.7/site-packages/nio/client/base_client.py", line 34, in <module>
    from ..crypto import Olm
  File "/home/ya/.local/lib/python3.7/site-packages/nio/crypto/__init__.py", line 1, in <module>
    from .sessions import (
  File "/home/ya/.local/lib/python3.7/site-packages/nio/crypto/sessions.py", line 18, in <module>
    import olm
  File "/home/ya/.local/lib/python3.7/site-packages/olm/__init__.py", line 12, in <module>
    from .utility import ed25519_verify, OlmVerifyError
  File "/home/ya/.local/lib/python3.7/site-packages/olm/utility.py", line 25, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: libolm.so.3: cannot open shared object file: No such file or directory
```

This can be circumvented with passing the path to the olm library via the `LD_LIBRARY_PATH` environment variable. Depending on your environment, this can read

    LD_LIBRARY_PATH=/usr/local/lib64/ pantalaimon https://matrix.host:443

and results in a running `pantalaimon` instance.

**Comment by poljar** [comment]
Yes, the library as usual needs to be found in your library path. The default location where libolm will be installed can and should be set with the standard make DESTDIR variable.

**Comment by almereyda** [comment]
Which location would `pantalaion` expect the `libolm.so.3` library in, other than its `make install` target?

**Comment by poljar** [comment]
That is entirely up to your system and its dynamic linker/loader. You can check out the man pages for ldconfig(8) and ld.so(8) if you are interested in the details.
My guess would be /usr/lib/.
