### ISSUE TITLE
traceback when sending message

### ISSUE THREAD

**Issue by symphorien** [matrix-org/pantalaimon#63]
```
juil. 31 20:56:00 nlaptop pantalaimon[1710]: Error handling request
juil. 31 20:56:00 nlaptop pantalaimon[1710]: Traceback (most recent call last):
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/if1f7acnj6wcgpr7dypgxfpvrq9cpwdm-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     resp = await task
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/if1f7acnj6wcgpr7dypgxfpvrq9cpwdm-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     resp = await handler(request)
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/lnf31q1500kh9iyhzdalyfqqjj8xq4l6-pantalaimon-0.6.5/lib/python3.8/site-packages/pantalaimon/daemon.py", line 862, in send_message
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     return await _send(self.conf.ignore_verification)
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/lnf31q1500kh9iyhzdalyfqqjj8xq4l6-pantalaimon-0.6.5/lib/python3.8/site-packages/pantalaimon/daemon.py", line 830, in _send
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     response = await client.room_send(
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/6q9kwgbfc37pzwcl8sjlbz9lsknhi183-python3.8-matrix-nio-0.14.1/lib/python3.8/site-packages/nio/client/async_client.py", line 1468, in room_send
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     await self.share_group_session(
juil. 31 20:56:00 nlaptop pantalaimon[1710]:   File "/nix/store/6q9kwgbfc37pzwcl8sjlbz9lsknhi183-python3.8-matrix-nio-0.14.1/lib/python3.8/site-packages/nio/client/async_client.py", line 1722, in share_group_session
juil. 31 20:56:00 nlaptop pantalaimon[1710]:     raise LocalProtocolError(
juil. 31 20:56:00 nlaptop pantalaimon[1710]: nio.exceptions.LocalProtocolError: Already sharing a group session for !someroomid
```

**Comment by symphorien** [comment]
After restarting pantalaimon, pantalaimon asked for confirmation to send a message to a room with unverified devices. I gave confirmation and the message was sent.

**Comment by poljar** [comment]
This is already fixed in nio: https://github.com/poljar/matrix-nio/commit/4654c7a1a7e39b496b107337977421aeb5953974.

Just needs a new release, will leave it open until then.

**Comment by poljar** [comment]
Release happened.
