### ISSUE TITLE
Traceback when sending message.

### ISSUE THREAD

**Issue by symphorien** [matrix-org/pantalaimon#67]
```
août 27 13:57:07 bete pantalaimon[1471]: Error handling request
août 27 13:57:07 bete pantalaimon[1471]: Traceback (most recent call last):
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/js82hk8n87rx6fgp2zsfxmnrpn387pzv-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
août 27 13:57:07 bete pantalaimon[1471]:     resp = await task
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/js82hk8n87rx6fgp2zsfxmnrpn387pzv-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
août 27 13:57:07 bete pantalaimon[1471]:     resp = await handler(request)
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/43icp1gxdg3gz9mi4jb01ykbmbv4n38g-pantalaimon-0.6.5/lib/python3.8/site-packages/pantalaimon/daemon.py", line 862, in send_message
août 27 13:57:07 bete pantalaimon[1471]:     return await _send(self.conf.ignore_verification)
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/43icp1gxdg3gz9mi4jb01ykbmbv4n38g-pantalaimon-0.6.5/lib/python3.8/site-packages/pantalaimon/daemon.py", line 830, in _send
août 27 13:57:07 bete pantalaimon[1471]:     response = await client.room_send(
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/wfqc9wyh3agzfn62la4h0pqwks925hcy-python3.8-matrix-nio-0.15.0/lib/python3.8/site-packages/nio/client/async_client.py", line 1526, in room_send
août 27 13:57:07 bete pantalaimon[1471]:     message_type, content = self.encrypt(
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/wfqc9wyh3agzfn62la4h0pqwks925hcy-python3.8-matrix-nio-0.15.0/lib/python3.8/site-packages/nio/client/base_client.py", line 114, in inner
août 27 13:57:07 bete pantalaimon[1471]:     return fn(self, *args, **kwargs)
août 27 13:57:07 bete pantalaimon[1471]:   File "/nix/store/wfqc9wyh3agzfn62la4h0pqwks925hcy-python3.8-matrix-nio-0.15.0/lib/python3.8/site-packages/nio/client/base_client.py", line 1186, in encrypt
août 27 13:57:07 bete pantalaimon[1471]:     raise MembersSyncError(
août 27 13:57:07 bete pantalaimon[1471]: nio.exceptions.MembersSyncError: The room is encrypted and the members aren't fully synced.
```
This is with nio 0.15.0 and pantalaimon 0.6.5 (I removed the version constraint on nio), but it also happens with nio 0.14.
This happens when sending a message (with fractal in my case). Restarting pantalaimon usually unblocks the situation the next time fractal retries.

**Comment by poljar** [comment]
This should be fixed with nio 0.15.1 with https://github.com/poljar/matrix-nio/pull/214.
