### ISSUE TITLE
Cannot install pantalaimon[ui]

### ISSUE THREAD

**Issue by mrjohnson22** [matrix-org/pantalaimon#68]
Installing pantaliamon with the `[ui]` extras hits an error.

This happens with python 3.8 on Fedora 32 Workstation Edition.

### Installing with pip
1. `python -m venv .venv && source .venv/bin/activate`
2. `pip install 'pantalaimon[ui]'`

Result:
```
  ERROR: Command errored out with exit status 1:
   command: /home/mr_johnson22/pantalaimon/.venv/bin/python /home/mr_johnson22/pantalaimon/.venv/lib64/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nja5vlot/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo
       cwd: None
  Complete output (31 lines):
  Collecting setuptools
    Using cached setuptools-50.1.0-py3-none-any.whl (784 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting pycairo
    Using cached pycairo-1.19.1.tar.gz (205 kB)
  Using legacy 'setup.py install' for pycairo, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, pycairo
      Running setup.py install for pycairo: started
      Running setup.py install for pycairo: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /home/mr_johnson22/pantalaimon/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hmmbanue/pycairo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hmmbanue/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_sox1me/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-nja5vlot/overlay --compile --install-headers /tmp/pip-build-env-nja5vlot/overlay/include/site/python3.8/pycairo
           cwd: /tmp/pip-install-hmmbanue/pycairo/
      Complete output (15 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/cairo
      copying cairo/__init__.py -> build/lib.linux-x86_64-3.8/cairo
      copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.8/cairo
      copying cairo/py.typed -> build/lib.linux-x86_64-3.8/cairo
      running build_ext
      Package cairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `cairo.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'cairo', required by 'virtual:world', not found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/mr_johnson22/pantalaimon/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hmmbanue/pycairo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hmmbanue/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_sox1me/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-nja5vlot/overlay --compile --install-headers /tmp/pip-build-env-nja5vlot/overlay/include/site/python3.8/pycairo Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mr_johnson22/pantalaimon/.venv/bin/python /home/mr_johnson22/pantalaimon/.venv/lib64/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nja5vlot/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo Check the logs for full command output.
```

The solution to this is to install development libraries & headers for cairo, but then it hits a different error:
1. `sudo dnf install cairo-devel`
2. `pip install 'pantalaimon[ui]'`

Result:
```
    ERROR: Command errored out with exit status 1:
     command: /home/mr_johnson22/pantalaimon/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qv4wvutb/dbus-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qv4wvutb/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sumx9z90
         cwd: /tmp/pip-install-qv4wvutb/dbus-python/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qv4wvutb/dbus-python/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Installing from source
1. `git clone https://github.com/matrix-org/pantalaimon.git && cd pantalaimon`
2. `python -m venv .venv && source .venv/bin/activate`
3. `pip install '.[ui]'`

Result:
```
    ERROR: Command errored out with exit status 1:
     command: /home/mr_johnson22/git/pantalaimon/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zm0j6hlc/dbus-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zm0j6hlc/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dsn2cuij
         cwd: /tmp/pip-install-zm0j6hlc/dbus-python/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-zm0j6hlc/dbus-python/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

`python setup.py install` works, but AIUI doesn't install the `[ui]` extras.

**Comment by poljar** [comment]
Should be fixed, seems like pip selected a very old python-dbus version for some reason. You'll still need to install C deps like cairo-devel or libolm but there's nothing we can do about that.
