### ISSUE TITLE
/send/m.room.message times out in some encrypted rooms

### ISSUE THREAD

**Issue by kakolisgay** [matrix-org/pantalaimon#75]
**Describe the bug**
Pantalaimon is timing out when sending messages in specific encrypted rooms.

**To Reproduce**
No idea

**Expected behavior**
Pantalaimon does it's job

**Screenshots**
Error from `matrix-bot-sdk`
```js
MatrixLiteClient (REQ-38150) Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/user/user/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:420:28)
    at ClientRequest.emit (events.js:314:20)
    at Socket.emitRequestTimeout (_http_client.js:769:9)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:326:22)
    at Socket._onTimeout (net.js:482:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
```

**Desktop (please complete the following information):**
 - OS: Rasbian
 - Browser: matrix-bot-sdk
 - Version: 0.5.8

**Additional context**
Only happening for one room, 301 users.

**Comment by kakolisgay** [comment]
> no reply in three days

this is why people don't use matrix

**Comment by poljar** [comment]
Sharing E2EE keys with 300 users which might have multiple devices will take some time, your bot seems to give up before the keys are shared.

**Comment by kakolisgay** [comment]
Encryption in that specific room worked fine for weeks, I doubt it's that. I suspect the bots session is being blocked by a user but I have no way of checking since it's a headless setup. Installing the dbus library required for panctl prevents pantalaimon from starting

**Comment by poljar** [comment]
E2EE keys may expire and will need to be re-shared, people delete/add device which expires E2EE keys as well, and the number of devices might have grown which might explain why it needs longer to share the keys. It might be something else, but the first thing to try will be to raise the timeout for your bot.

**Comment by kakolisgay** [comment]
I can't do that. `matrix-bot-js` provides no way to increase the ttl for sending events

**Comment by poljar** [comment]
Can you perhaps confirm that this indeed is the issue using `curl` to send a message?

**Comment by kakolisgay** [comment]
There isn't going to be any difference between `matrix-bot-js` sending a message to the room ([MatrixClient.ts#987](https://github.com/turt2live/matrix-bot-sdk/blob/master/src/MatrixClient.ts#L982)) and curl sending a message to the room. The issue isn't just the `/send/${type}/${track}` timing out either, this bug freezes up pantalaimon entirely for a few seconds

**Comment by Yoric** [comment]
I encountered the same issue, briefly, in a room with exactly 2 users, me and my bot.

1. Yesterday, my bot worked nicely.
2. Today, I connected with an element-web built and deployed by me. My bot started `ESOCKETTIMEDOUT` whenever I attemped to send a message.
3. I closed the tab with this unusual element-web then reopened it.
4. The bot resumed working correctly.
