### ISSUE TITLE
Error handling request

### ISSUE THREAD

**Issue by almereyda** [matrix-org/pantalaimon#8]
After logging in to `pantalaimon` with Fractal, it raises

```
Error handling request
Traceback (most recent call last):
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/ya/.local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 89, in router
    return(web.Response(text=await resp.text()))
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1010, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Then, when trying to display an encrypted channel through fractal, this repeats indefinitely:

```
Error handling request
Traceback (most recent call last):
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/ya/.local/lib/python3.7/site-packages/pantalaimon-0.1-py3.7.egg/pantalaimon/daemon.py", line 89, in router
    return(web.Response(text=await resp.text()))
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1010, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by almereyda** [comment]
The same bytes also appear in stdout when using Quaternion.
