### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by almereyda** [matrix-org/pantalaimon#9]
An instance of ConnectionResetError is not handled:

```
Unhandled exception
Traceback (most recent call last):
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/home/ya/.local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

This occured when using Fractal.

**Comment by poljar** [comment]
This seems to be an upstream issue: https://github.com/aio-libs/aiohttp/issues/3648

**Comment by poljar** [comment]
I believe this has been fixed upstream in aiohttp.
