### ISSUE TITLE
/profile: aiohttp error causes a HTTP 500 response

### ISSUE THREAD

**Issue by jaller94** [matrix-org/pantalaimon#92]
**Describe the bug**
When a Slack bridge gets restarted, rooms and users got synced.
One of our Slack bridges saw a lot of HTTP 500s from Pantalaimon when trying to set avatar_urls.

```
ERROR bridge [-] PUT http://pantalaimonclient:8008/_matrix/client/r0/profile/%40_slack_foo_U0123456789%3Afoo.ems.host/avatar_url (AS) HTTP 500 Error: "500 Internal Server Error\n\nServer got itself in trouble"
```

**To Reproduce**
Don't know.

**Expected behavior**
Pantalaimon's response shouldn't be 500 for a catchable error.

> think that's an aiohttp error
> HTTPInternalServerError: An exception for 500 Server got itself in trouble, a subclass of 
> which gets thrown if pantalaimon doesn't catch an exception
> this is the method that gets called for the /profile request https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L1226
> ~poljar

**Comment by poljar** [comment]
Is there a way to fish out more info? Is this happening regularly? Can you run a modified pantalaimon? E.g. adding `debug=True` [here](https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/main.py#L62) would print the traceback in the response.

I looked at the affected method but couldn't see anything obviously wrong, as is I'm not sure how actionable this issue is.

**Comment by Half-Shot** [comment]
@poljar this seems to happen for every request. I can do the debug thing to see.

**Comment by Half-Shot** [comment]
```
May-14 15:50:50.260 INFO bridge [-] PUT http://pantalaimonclient:8008/_matrix/client/r0/profile/%40_slack_half-shot_U017GRM7U06%3Abridge-box-2-staging.modular.im/avatar_url (AS) Body: "{\"avatar_url\":\"\"}"
May-14 15:50:50.275 ERROR bridge [-] PUT http://pantalaimonclient:8008/_matrix/client/r0/profile/%40_slack_half-shot_U017GRM7U06%3Abridge-box-2-staging.modular.im/avatar_url (AS) HTTP 500 Error: "500 Internal Server Error\n\nTraceback (mo
st recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py\", line 422, in _handle_request\n    resp = await self._request_handler(request)\n  File \"/usr/local/lib/python3.8/site-packages/aiohttp/web_a
pp.py\", line 499, in _handle\n    resp = await handler(request)\n  File \"/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py\", line 1245, in profile\n    content = await self._map_decrypted_uri(\"avatar_url\", content, request
, client)\n  File \"/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py\", line 870, in _map_decrypted_uri\n    response, decrypted_file = await self._load_decrypted_file(media_info.mxc_server, media_info.mxc_path,\nAttributeErro
r: 'LRUCache' object has no attribute 'mxc_server'\n"
May-14 15:50:50.278 ERROR TeamSyncer There was an issue when trying to sync teams: Error: Server returned 500 error: 500 Internal Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py", line 1245, in profile
    content = await self._map_decrypted_uri("avatar_url", content, request, client)
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/daemon.py", line 870, in _map_decrypted_uri
    response, decrypted_file = await self._load_decrypted_file(media_info.mxc_server, media_info.mxc_path,
AttributeError: 'LRUCache' object has no attribute 'mxc_server'

    at parseErrorResponse (/usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:829:13)
    at /usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:782:17
    at /usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:716:9
    at Request._callback (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:79:17)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28) {
  httpStatus: 500
}
```

**Comment by poljar** [comment]
Thanks, I see the problem now, not yet completely sure how to fix but we'll get there.

**Comment by poljar** [comment]
If you could confirm that #96 fixes this, that would be great.

**Comment by jaller94** [comment]
After we had pushed a new release, I didn't see the errors. I assume that this got fixed. :+1:

**Comment by poljar** [comment]
Thanks for confirming.
