### ISSUE TITLE
--data-path gives AssertionError

### ISSUE THREAD

**Issue by atomtm** [matrix-org/pantalaimon#97]
**Describe the bug**
Using the `--data-path` switch gives the following error:
```
DEBUG: pantalaimon: UI loop received message UpdateUsersMessage(server='local-matrix', user_id='@test:test.com', device_id='FEWFFFEWT')
Error handling request
Traceback (most recent call last):
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/pantalaimon/daemon.py", line 680, in login
    await self.start_pan_client(
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/pantalaimon/daemon.py", line 629, in start_pan_client
    self.store.save_access_token(
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/nio/store/database.py", line 40, in inner
    return fn(self, *args, **kwargs)
  File "/home/test/matrix-pantalaimon/venv/lib/python3.8/site-packages/pantalaimon/store.py", line 395, in save_access_token
    assert account
AssertionError
```

**To Reproduce**
run pantalaimon with `pantalaimon --data-path some_path`

**Desktop (please complete the following information):**
Ubuntu 20.04 server

**Additional context**
pantalaimon, version 0.9.3

**Comment by chookity-pokk** [comment]
This is a few years old but your stack trace is [failing here](https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/store.py#L405) but also that fails because the account doesn't seem to exist (as seen by the returning on [None here](https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/store.py#L198-L205)). When that returns None, then the assertion in `save_account` fails. So the issue is likely that the account info is incorrect.
